---
openshift_azure_clusterid: "{{ openshift_clusterid | default('default') }}"
openshift_azure_prefix: "{{ lookup('env', 'INSTANCE_PREFIX') | default('') }}"

openshift_azure_create_resource_group: True
openshift_azure_resource_group_name: "{{ openshift_azure_clusterid }}"
openshift_azure_resource_location: eastus

openshift_azure_root_image_ns: "{{ openshift_azure_resource_group_name }}"
openshift_azure_base_image_ns: "{{ openshift_azure_resource_group_name }}"

openshift_azure_image_build_base: "{{ not (openshift_node_bootstrap | default(False)) }}"

openshift_azure_base_image_query_starts_with: "{{ 'rhel7.4-base-' if openshift_deployment_type == 'openshift-enterprise' else 'centosbase-' }}"
openshift_azure_image_query_starts_with: "{{ 'openshift-gi-' if openshift_deployment_type == 'openshift-enterprise' else 'origin-gi-' }}"
openshift_azure_base_image_query: |
  az image list -g {{ openshift_azure_base_image_ns | quote }} -o json --query "[?starts_with(name, '{{ openshift_azure_base_image_query_starts_with }}')].name | sort(@) | reverse(@) | [0]" | tr -d '"'
openshift_azure_image_query: |
  az image list -g {{ openshift_azure_resource_group_name | quote }} -o json --query "[?starts_with(name, '{{ openshift_azure_image_query_starts_with }}')].name | sort(@) | reverse(@) | [0]" | tr -d '"'
openshift_azure_base_image: "{{ lookup('pipe', openshift_azure_base_image_query) }}"
openshift_azure_image: "{{ lookup('pipe', openshift_azure_image_query) }}"

openshift_azure_image_tags: {}

openshift_azure_storage_account_name: "{{ openshift_azure_clusterid }}"
openshift_azure_storage_account_container: images
openshift_azure_storage_account_type: Standard_LRS
openshift_azure_subnet_prefix: 172.31.48.0/20
openshift_azure_virtual_network_address_prefixes:
- 172.31.48.0/20
- 172.31.32.0/20
- 172.31.16.0/20

# network
openshift_azure_virtual_network_name: "{{ openshift_azure_clusterid }}"

# public IPs
openshift_azure_public_ip_alloc_method: Static
openshift_azure_public_ips:
- name: "{{ openshift_azure_clusterid }}"
  resource_group: "{{ openshift_azure_resource_group_name }}"
  alloc_method: "{{ openshift_azure_public_ip_alloc_method }}"

# securitygroups
openshift_azure_sg_name: "{{ openshift_azure_clusterid }}"
openshift_azure_sg_rules:
- name: SSH
  protocol: Tcp
  destination_port_range: 22
  access: Allow
  priority: 101
  direction: Inbound

# networkinterface
openshift_azure_subnet_name: "{{ openshift_azure_clusterid }}"
openshift_azure_nw_interfaces:
- name: "{{ openshift_azure_clusterid }}"
  resource_group: "{{ openshift_azure_resource_group_name }}"
  virtual_network: "{{ openshift_azure_virtual_network_name }}"
  subnet: "{{ openshift_azure_subnet_name }}"
  public_ip: "{{ openshift_azure_public_ips[0].name }}"
  security_group: "{{ openshift_azure_sg_name }}"

# vm settings
openshift_azure_vm_name: "{{ openshift_azure_clusterid }}"
openshift_azure_vm_admin_username: openshift
openshift_azure_vm_ssh_pw_enabled: "{{ True if openshift_azure_vm_admin_password is defined else False }}"
openshift_azure_vm_image:
  name: "{{ openshift_azure_base_image }}"
  resource_group: "{{ openshift_azure_base_image_ns | default(openshift_azure_resource_group_name) }}"

openshift_azure_vm_data_disks:
- managed_disk_type: Premium_LRS
  disk_size_gb: 100
  storage_container_name: images
  caching: ReadOnly
  storage_blob_name: "{{ openshift_azure_vm_storage_blob }}"
  storage_account_name: "{{ openshift_azure_storage_account_name }}"

openshift_azure_vm_storage_container: "{{ openshift_azure_clusterid }}"

openshift_azure_vm_ssh_public_keys: []
#- path: /root/.ssh/authorized_keys
#  key_data: "{{ openshift_azure_public_ssh_key }}"

openshift_azure_vm_size: Standard_D4s_v3

openshift_azure_vm_keep_storage: true

openshift_azure_credentials_file: "{{ ansible_user_dir | default('/opt/app-root/src') }}/.azure/credentials"
openshift_azure_subscription_id: "{{ lookup('ini', 'subscription_id section=default file=' + openshift_azure_credentials_file) }}"
openshift_azure_client_id: "{{ lookup('ini', 'client_id section=default file=' + openshift_azure_credentials_file) }}"
openshift_azure_service_secret: "{{ lookup('ini', 'secret section=default file=' + openshift_azure_credentials_file) }}"
openshift_azure_tenant_id: "{{ lookup('ini', 'tenant section=default file=' + openshift_azure_credentials_file) }}"

# used in launch.yml for the openshift.json
openshift_azure_acsengine_urls: []

openshift_azure_acsengine_template_dns_prefix: "{{ openshift_azure_prefix }}-{{ openshift_azure_clusterid }}"
openshift_azure_acsengine_template_image_name: "{{ openshift_azure_image }}"
openshift_azure_acsengine_template_image_rg: "{{ openshift_azure_base_image_ns }}"

openshift_azure_acsengine_template_edits: []

# image publishing variables
# openshift_azure_offer:

# offer template params #
# openshift_azure_templ_display_text:
# openshift_azure_templ_allowed_subscriptions: []
# openshift_azure_templ_description:
# openshift_azure_templ_hero_logo:
# openshift_azure_templ_large_logo:
# openshift_azure_templ_medium_logo:
# openshift_azure_templ_small_logo:
# openshift_azure_templ_wide_logo:
# openshift_azure_templ_offer_id: "{{ openshift_azure_offer }}"
# openshift_azure_templ_plan_id:
# openshift_azure_templ_publisher:
# openshift_azure_templ_privacy_url:
# openshift_azure_templ_eng_contact_email:
# openshift_azure_templ_eng_contact:
# openshift_azure_templ_eng_contact_phone:
# openshift_azure_templ_support_contact_email:
# openshift_azure_templ_support_contact:
# openshift_azure_templ_support_contact_phone:
# openshift_azure_templ_tou:
# openshift_azure_templ_title:
# openshift_azure_templ_os:
# openshift_azure_templ_os_type:
# openshift_azure_templ_description:
# openshift_azure_templ_summary:
# openshift_azure_templ_data_vhd_url:
# openshift_azure_templ_os_vhd_url:
# openshift_azure_templ_version:
# openshift_azure_templ_vm_images: |
#   "{{ openshift_azure_templ_version }}":
#     lunVhdDetails:
#     - lunNumber: '0'
#       lunVhdUrl: '{{ openshift_azure_templ_data_vhd_url}}'
#     osVhdUrl: "{{ openshift_azure_templ_os_vhd_url }}"
